import argparse
import asyncio
import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

from seimei import LLMClient, load_run_messages

EXP_DIR = Path("exp8_csv_small")
DEFAULT_DATASET_PATH = EXP_DIR / "dataset.json"
DEFAULT_INPUT_PATH = EXP_DIR / "train_v4_eval_results2.json"
DEFAULT_OUTPUT_PATH = EXP_DIR / "train_v4_eval_results2_analysis.json"
DEFAULT_LOG_DIR = Path("seimei_runs")
DEFAULT_LLM_MODEL = "gpt-5-nano"

BASE_WIN_REASON_SYSTEM_PROMPT = (
    "You are comparing two experiment runs that answer the same CSV reasoning question. "
    "Explain why the baseline answer (without injected knowledge) beat the knowledge-assisted answer "
    "and why the injected knowledge was useless. Use the provided transcripts and outputs for evidence, "
    "cite both run IDs, and keep the explanation to 2-4 sentences."
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Retrofit train_v4_eval outputs with the enhanced base-win analysis."
    )
    parser.add_argument(
        "--dataset-path",
        type=Path,
        default=DEFAULT_DATASET_PATH,
        help="Dataset JSON used to recover the original question and reference answer.",
    )
    parser.add_argument(
        "--input-path",
        type=Path,
        default=DEFAULT_INPUT_PATH,
        help="Existing results JSON generated by train_v4_eval.py.",
    )
    parser.add_argument(
        "--output-path",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="Where to store the enriched analysis JSON.",
    )
    parser.add_argument(
        "--log-dir",
        type=Path,
        default=DEFAULT_LOG_DIR,
        help="Directory that holds the seimei run logs referenced by run_id.",
    )
    parser.add_argument(
        "--llm-model",
        default=DEFAULT_LLM_MODEL,
        help="Model name passed to LLMClient when generating explanations.",
    )
    parser.add_argument(
        "--llm-base-url",
        default=None,
        help="Optional base URL for an OpenAI-compatible endpoint.",
    )
    parser.add_argument(
        "--llm-api-key",
        default=None,
        help="Optional API key for the LLM endpoint (falls back to OPENAI_API_KEY).",
    )
    parser.add_argument(
        "--llm-api-key-env",
        default=None,
        help="Environment variable name that stores the API key (checked before OPENAI_API_KEY).",
    )
    return parser.parse_args()


def compute_entry_id(dataset_entry: Dict[str, Any], index: int) -> str:
    explicit_keys = ["id", "ID", "question_id", "QuestionID"]
    for key in explicit_keys:
        value = dataset_entry.get(key)
        if value:
            return str(value)
    csv_path = str(dataset_entry.get("CSVPath") or "").strip()
    if csv_path:
        return csv_path
    topic = str(dataset_entry.get("Topic") or "").strip()
    hyper = dataset_entry.get("HyperParamIndex")
    sample = dataset_entry.get("SampleIndex")
    parts = [f"idx_{index:05d}"]
    if topic:
        parts.append(topic)
    if hyper not in (None, ""):
        parts.append(f"hp_{hyper}")
    if sample not in (None, ""):
        parts.append(f"sample_{sample}")
    return "|".join(parts)


def _strip_code_fences(text: str) -> str:
    snippet = text.strip()
    if snippet.startswith("```"):
        lines = snippet.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        snippet = "\n".join(lines).strip()
    return snippet


def _parse_json_response(raw: str) -> Dict[str, Any]:
    cleaned = _strip_code_fences(raw)
    candidates = [cleaned]
    if "{" in cleaned and "}" in cleaned:
        start = cleaned.find("{")
        end = cleaned.rfind("}")
        if 0 <= start < end:
            candidates.append(cleaned[start : end + 1])
    for candidate in candidates:
        try:
            data = json.loads(candidate)
            if isinstance(data, dict):
                return data
        except json.JSONDecodeError:
            continue
    return {}


def _shorten_text(value: Any, limit: int = 200) -> str:
    text = str(value or "").strip()
    if not text:
        return ""
    if len(text) <= limit:
        return text
    return text[: max(limit - 3, 0)].rstrip() + "..."


def _normalize_transcript(
    entries: Sequence[Dict[str, Any]],
    *,
    max_agent_step: Optional[int] = None,
) -> List[Dict[str, Any]]:
    filtered: List[Dict[str, Any]] = []
    agent_seen = 0
    for msg in entries:
        if not isinstance(msg, dict):
            continue
        role = str(msg.get("role") or "").lower()
        if role == "assistant":
            continue
        filtered.append(dict(msg))
        if role == "agent":
            agent_seen += 1
            if max_agent_step is not None and agent_seen >= max_agent_step:
                break
    return filtered


def load_run_transcript_by_id(
    run_id: Optional[str],
    log_dir: Path,
    *,
    max_agent_step: Optional[int] = None,
) -> List[Dict[str, Any]]:
    run_id_str = str(run_id or "").strip()
    if not run_id_str:
        return []
    try:
        raw_messages = load_run_messages(run_id_str, runs_dir=log_dir, step=max_agent_step)
    except FileNotFoundError:
        return []
    return _normalize_transcript(raw_messages, max_agent_step=max_agent_step)


def _format_messages_for_prompt(
    messages: Sequence[Dict[str, Any]],
    *,
    limit_chars: int = 4000,
) -> str:
    if not messages:
        return ""
    serialized = json.dumps(messages, ensure_ascii=False, indent=2)
    if len(serialized) <= limit_chars:
        return serialized
    return serialized[: max(limit_chars - 3, 0)].rstrip() + "..."


async def generate_base_win_reason(
    llm_client: LLMClient,
    *,
    entry_id: str,
    question: str,
    reference_answer: str,
    base_trial: Dict[str, Any],
    knowledge_trial: Dict[str, Any],
    base_messages: Sequence[Dict[str, Any]],
    knowledge_messages: Sequence[Dict[str, Any]],
    knowledge_entries: Sequence[Dict[str, Any]],
) -> Optional[str]:
    base_run_id = base_trial.get("run_id")
    knowledge_run_id = knowledge_trial.get("run_id")
    base_output = _shorten_text(base_trial.get("output"), 2000)
    knowledge_output = _shorten_text(knowledge_trial.get("output"), 2000)
    knowledge_json = (
        _shorten_text(json.dumps(knowledge_entries, ensure_ascii=False, indent=2), 2000)
        if knowledge_entries
        else "[]"
    )
    base_messages_text = _format_messages_for_prompt(base_messages, limit_chars=4000)
    knowledge_messages_text = _format_messages_for_prompt(knowledge_messages, limit_chars=4000)
    prompt = (
        "Explain why the base model outperformed the knowledge-injected model.\n\n"
        f"Dataset entry ID: {entry_id}\n"
        f"Question:\n{question}\n\n"
        f"Reference answer:\n{reference_answer}\n\n"
        f"Base run ID: {base_run_id} | Score: {base_trial.get('score')}\n"
        f"Base output:\n{base_output}\n\n"
        f"Base run messages:\n{base_messages_text}\n\n"
        f"Knowledge run ID: {knowledge_run_id} | Score: {knowledge_trial.get('score')}\n"
        f"Knowledge output:\n{knowledge_output}\n\n"
        f"Injected knowledge entries:\n{knowledge_json}\n\n"
        f"Knowledge run messages:\n{knowledge_messages_text}\n"
    )
    try:
        response, _ = await llm_client.chat(
            messages=[{"role": "user", "content": prompt}],
            system=BASE_WIN_REASON_SYSTEM_PROMPT,
        )
    except Exception:
        return None
    parsed = _parse_json_response(response)
    reason = parsed.get("reason")
    if isinstance(reason, str) and reason.strip():
        return reason.strip()
    return None


async def build_base_win_analysis(
    *,
    entry_id: str,
    base_trials: Sequence[Dict[str, Any]],
    knowledge_trials: Sequence[Dict[str, Any]],
    knowledge_entries: Sequence[Dict[str, Any]],
    base_mean_score: float,
    knowledge_mean_score: float,
    question: str,
    reference_answer: str,
    log_dir: Path,
    llm_client: LLMClient,
) -> Optional[Dict[str, Any]]:
    if base_mean_score <= knowledge_mean_score:
        return None
    if not base_trials or not knowledge_trials:
        return None

    def trial_score(trial: Dict[str, Any]) -> float:
        try:
            return float(trial.get("score") or 0.0)
        except (TypeError, ValueError):
            return 0.0

    base_best = max(base_trials, key=trial_score)
    knowledge_worst = min(knowledge_trials, key=trial_score)
    base_score = round(trial_score(base_best), 2)
    knowledge_score = round(trial_score(knowledge_worst), 2)
    score_delta = round(base_score - knowledge_score, 2)

    knowledge_descriptions: List[str] = []
    for entry in knowledge_entries:
        text = entry.get("text") or entry.get("original_text")
        if not text:
            continue
        step = entry.get("step")
        prefix = f"step {step}: " if step not in (None, "") else ""
        knowledge_descriptions.append(_shorten_text(f"{prefix}{text}", 160))
    knowledge_summary = (
        "; ".join(knowledge_descriptions) if knowledge_descriptions else "no manual knowledge was injected"
    )

    base_messages = load_run_transcript_by_id(base_best.get("run_id"), log_dir)
    knowledge_messages = load_run_transcript_by_id(knowledge_worst.get("run_id"), log_dir)
    reason = await generate_base_win_reason(
        llm_client,
        entry_id=entry_id,
        question=question,
        reference_answer=reference_answer,
        base_trial=base_best,
        knowledge_trial=knowledge_worst,
        base_messages=base_messages,
        knowledge_messages=knowledge_messages,
        knowledge_entries=knowledge_entries,
    )
    if not reason:
        base_feedback = _shorten_text(base_best.get("score_feedback")) or "reward model shared no feedback"
        knowledge_feedback = _shorten_text(knowledge_worst.get("score_feedback")) or "reward model shared no feedback"
        base_run_id = base_best.get("run_id") or "unknown base run"
        knowledge_run_id = knowledge_worst.get("run_id") or "unknown knowledge run"
        reason = (
            f"{entry_id}: base run {base_run_id} scored {base_score} ({base_feedback}) "
            f"while knowledge run {knowledge_run_id} fell to {knowledge_score} ({knowledge_feedback}). "
            f"The injected cues ({knowledge_summary}) failed to improve the reasoning."
        )

    analysis = {
        "reason": reason,
        "score_delta_vs_worst_knowledge": score_delta,
        "base_best_trial": {
            "run_id": base_best.get("run_id"),
            "score": base_score,
            "score_feedback": base_best.get("score_feedback"),
        },
        "knowledge_worst_trial": {
            "run_id": knowledge_worst.get("run_id"),
            "score": knowledge_score,
            "score_feedback": knowledge_worst.get("score_feedback"),
        },
        "compared_run_ids": {
            "base_best": base_best.get("run_id"),
            "knowledge_worst": knowledge_worst.get("run_id"),
        },
        "knowledge_used": [dict(entry) for entry in knowledge_entries],
        "base_mean_score": round(float(base_mean_score or 0.0), 2),
        "knowledge_mean_score": round(float(knowledge_mean_score or 0.0), 2),
    }
    return analysis


def build_eval_summary(entries: List[Dict[str, Any]]) -> Dict[str, Any]:
    if not entries:
        return {
            "total_problems": 0,
            "mean_score_improvement": 0.0,
            "base_vs_final": [],
            "overall_base_mean": 0.0,
            "overall_final_mean": 0.0,
            "win_loss_tie": {"win": 0, "tie": 0, "loss": 0},
        }
    base_vs_final: List[List[float]] = []
    improvements: List[float] = []
    base_win_reasons: List[Dict[str, str]] = []
    for entry in entries:
        base_score = entry.get("base_rerun_mean_score")
        final_score = entry.get("final_rerun_mean_score")
        if base_score is None:
            base_score = entry.get("base", {}).get("score", 0.0)
        if final_score is None:
            final_score = entry.get("final_score", 0.0)
        base_val = round(float(base_score), 2)
        final_val = round(float(final_score), 2)
        base_vs_final.append([base_val, final_val])
        improvements.append(final_val - base_val)
        analysis = entry.get("base_win_analysis")
        if analysis and analysis.get("reason"):
            base_win_reasons.append(
                {
                    "id": entry.get("id"),
                    "reason": analysis["reason"],
                }
            )
    total = len(base_vs_final)
    mean_improvement = round(sum(improvements) / total, 4) if total else 0.0
    wins = sum(1 for diff in improvements if diff > 0)
    ties = sum(1 for diff in improvements if diff == 0)
    losses = total - wins - ties
    overall_base_mean = (
        round(sum(pair[0] for pair in base_vs_final) / total, 4) if total else 0.0
    )
    overall_final_mean = (
        round(sum(pair[1] for pair in base_vs_final) / total, 4) if total else 0.0
    )
    summary = {
        "total_problems": total,
        "mean_score_improvement": mean_improvement,
        "base_vs_final": base_vs_final,
        "overall_base_mean": overall_base_mean,
        "overall_final_mean": overall_final_mean,
        "win_loss_tie": {"win": wins, "tie": ties, "loss": losses},
    }
    if base_win_reasons:
        summary["base_win_reasons"] = base_win_reasons
    return summary


def load_dataset_index(dataset_path: Path) -> Tuple[List[Dict[str, Any]], Dict[str, Dict[str, Any]]]:
    dataset = json.loads(dataset_path.read_text(encoding="utf-8"))
    index: Dict[str, Dict[str, Any]] = {}
    for idx, entry in enumerate(dataset):
        entry_id = compute_entry_id(entry, idx)
        index[entry_id] = entry
    return dataset, index


def load_existing_results(input_path: Path) -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    payload = json.loads(input_path.read_text(encoding="utf-8"))
    if isinstance(payload, dict):
        detail = payload.get("detail") or []
        if not isinstance(detail, list):
            detail = []
        summary = payload.get("summary") or {}
    elif isinstance(payload, list):
        detail = payload
        summary = {}
    else:
        detail = []
        summary = {}
    return detail, summary


async def analyze_existing_results(args: argparse.Namespace) -> None:
    dataset, dataset_index = load_dataset_index(args.dataset_path)
    detail_entries, _ = load_existing_results(args.input_path)
    llm_client = LLMClient(
        model=args.llm_model,
        base_url=args.llm_base_url,
        api_key=args.llm_api_key,
        api_key_env=args.llm_api_key_env,
    )
    log_dir = Path(args.log_dir)

    updated_entries: List[Dict[str, Any]] = []
    for idx, entry in enumerate(detail_entries):
        entry_id = str(entry.get("id") or "").strip()
        if not entry_id:
            if idx < len(dataset):
                entry_id = compute_entry_id(dataset[idx], idx)
                entry["id"] = entry_id
            else:
                entry_id = f"idx_{idx:05d}"
                entry["id"] = entry_id
        dataset_entry = dataset_index.get(entry_id)
        if not dataset_entry:
            print(f"[train_v4_eval3] Warning: missing dataset row for entry {entry_id}, skipping base-win analysis.")
            updated_entries.append(entry)
            continue

        fair_comparison = entry.get("fair_comparison") or {}
        base_trials = fair_comparison.get("base_trials") or []
        knowledge_trials = fair_comparison.get("knowledge_trials") or []
        base_mean = entry.get("base_rerun_mean_score")
        if base_mean is None:
            base_mean = fair_comparison.get("base_mean_score")
        if base_mean is None:
            base_mean = entry.get("base", {}).get("score", 0.0)
        knowledge_mean = entry.get("final_rerun_mean_score")
        if knowledge_mean is None:
            knowledge_mean = fair_comparison.get("knowledge_mean_score")
        if knowledge_mean is None:
            knowledge_mean = entry.get("final_score", 0.0)

        knowledge_entries = entry.get("selected_knowledge") or []
        analysis = await build_base_win_analysis(
            entry_id=entry_id,
            base_trials=base_trials,
            knowledge_trials=knowledge_trials,
            knowledge_entries=[dict(item) for item in knowledge_entries],
            base_mean_score=float(base_mean or 0.0),
            knowledge_mean_score=float(knowledge_mean or 0.0),
            question=dataset_entry.get("Question", ""),
            reference_answer=dataset_entry.get("CorrectAnswer", ""),
            log_dir=log_dir,
            llm_client=llm_client,
        )
        if analysis:
            entry["base_win_analysis"] = analysis
        updated_entries.append(entry)

    summary = build_eval_summary(updated_entries)
    payload = {
        "summary": summary,
        "detail": updated_entries,
        "source_results_path": str(args.input_path),
    }
    args.output_path.parent.mkdir(parents=True, exist_ok=True)
    args.output_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"[train_v4_eval3] Saved enriched analysis to {args.output_path}")


def main() -> None:
    args = parse_args()
    asyncio.run(analyze_existing_results(args))


if __name__ == "__main__":
    main()
